# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ps.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1053, 791)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(140, 50, 791, 681))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.taurusLCD_current = TaurusLCD(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.taurusLCD_current.sizePolicy().hasHeightForWidth())
        self.taurusLCD_current.setSizePolicy(sizePolicy)
        self.taurusLCD_current.setMinimumSize(QtCore.QSize(0, 0))
        self.taurusLCD_current.setMaximumSize(QtCore.QSize(20, 16777215))
        self.taurusLCD_current.setSmallDecimalPoint(True)
        self.taurusLCD_current.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.taurusLCD_current.setProperty("value", 20.0)
        self.taurusLCD_current.setObjectName("taurusLCD_current")
        self.gridLayout.addWidget(self.taurusLCD_current, 5, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.dial_current = QtWidgets.QDial(self.gridLayoutWidget)
        self.dial_current.setAcceptDrops(False)
        self.dial_current.setNotchesVisible(True)
        self.dial_current.setObjectName("dial_current")
        self.gridLayout.addWidget(self.dial_current, 5, 3, 1, 1)
        self.taurusLabel_5 = TaurusLabel(self.gridLayoutWidget)
        self.taurusLabel_5.setAlignment(QtCore.Qt.AlignCenter)
        self.taurusLabel_5.setObjectName("taurusLabel_5")
        self.gridLayout.addWidget(self.taurusLabel_5, 6, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 8, 1, 1, 1)
        self.taurusLabel_4 = TaurusLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.taurusLabel_4.sizePolicy().hasHeightForWidth())
        self.taurusLabel_4.setSizePolicy(sizePolicy)
        self.taurusLabel_4.setAlignment(QtCore.Qt.AlignCenter)
        self.taurusLabel_4.setObjectName("taurusLabel_4")
        self.gridLayout.addWidget(self.taurusLabel_4, 5, 2, 1, 1)
        self.taurusLCD_power = TaurusLCD(self.gridLayoutWidget)
        self.taurusLCD_power.setMinimumSize(QtCore.QSize(0, 0))
        self.taurusLCD_power.setSmallDecimalPoint(True)
        self.taurusLCD_power.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.taurusLCD_power.setProperty("value", 100.0)
        self.taurusLCD_power.setObjectName("taurusLCD_power")
        self.gridLayout.addWidget(self.taurusLCD_power, 6, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.taurusLabel = TaurusLabel(self.gridLayoutWidget)
        self.taurusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.taurusLabel.setObjectName("taurusLabel")
        self.gridLayout.addWidget(self.taurusLabel, 2, 1, 1, 3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 1, 1, 1, 1)
        self.dial_voltage = QtWidgets.QDial(self.gridLayoutWidget)
        self.dial_voltage.setEnabled(True)
        self.dial_voltage.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.dial_voltage.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.dial_voltage.setAutoFillBackground(False)
        self.dial_voltage.setMaximum(30)
        self.dial_voltage.setSingleStep(1)
        self.dial_voltage.setSliderPosition(0)
        self.dial_voltage.setOrientation(QtCore.Qt.Horizontal)
        self.dial_voltage.setInvertedAppearance(False)
        self.dial_voltage.setInvertedControls(False)
        self.dial_voltage.setNotchesVisible(True)
        self.dial_voltage.setObjectName("dial_voltage")
        self.gridLayout.addWidget(self.dial_voltage, 4, 3, 1, 1)
        self.taurusLCD_voltage = TaurusLCD(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.taurusLCD_voltage.sizePolicy().hasHeightForWidth())
        self.taurusLCD_voltage.setSizePolicy(sizePolicy)
        self.taurusLCD_voltage.setMinimumSize(QtCore.QSize(0, 0))
        self.taurusLCD_voltage.setSmallDecimalPoint(True)
        self.taurusLCD_voltage.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.taurusLCD_voltage.setProperty("value", 20.0)
        self.taurusLCD_voltage.setObjectName("taurusLCD_voltage")
        self.gridLayout.addWidget(self.taurusLCD_voltage, 4, 1, 1, 1)
        self.taurusLabel_6 = TaurusLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.taurusLabel_6.sizePolicy().hasHeightForWidth())
        self.taurusLabel_6.setSizePolicy(sizePolicy)
        self.taurusLabel_6.setAlignment(QtCore.Qt.AlignCenter)
        self.taurusLabel_6.setObjectName("taurusLabel_6")
        self.gridLayout.addWidget(self.taurusLabel_6, 4, 2, 1, 1)
        self.taurusLed = TaurusLed(self.gridLayoutWidget)
        self.taurusLed.setAspectRatioMode(QtCore.Qt.KeepAspectRatio)
        self.taurusLed.setTransformationMode(QtCore.Qt.SmoothTransformation)
        self.taurusLed.setAlignment(QtCore.Qt.AlignCenter)
        self.taurusLed.setObjectName("taurusLed")
        self.gridLayout.addWidget(self.taurusLed, 7, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.taurusCommandButton_2 = TaurusCommandButton(self.gridLayoutWidget)
        self.taurusCommandButton_2.setObjectName("taurusCommandButton_2")
        self.gridLayout.addWidget(self.taurusCommandButton_2, 7, 2, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.taurusLabel_5.setText(_translate("Form", "-----"))
        self.taurusLabel_4.setText(_translate("Form", "-----"))
        self.taurusLabel.setText(_translate("Form", "-----"))
        self.taurusLabel_6.setText(_translate("Form", "-----"))
        self.taurusLed.setLedColor(_translate("Form", "green"))
        self.taurusLed.setOffColor(_translate("Form", "red"))
        self.taurusCommandButton_2.setText(_translate("Form", "Power On/Off"))

from taurus.qt.qtgui.button import TaurusCommandButton
from taurus.qt.qtgui.display import TaurusLCD, TaurusLabel, TaurusLed
